# Generated by Django 5.1.1 on 2024-09-14 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programmer',
            old_name='fullnam',
            new_name='fullname',
        ),
    ]
