# Generated by Django 5.1.1 on 2024-09-14 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_nombre_persona_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
