# Generated by Django 5.1.1 on 2024-09-14 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_persona_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='email',
            new_name='correo',
        ),
    ]
