# Generated by Django 5.1.1 on 2024-09-16 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_email_persona_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='password',
            field=models.CharField(max_length=250),
        ),
    ]
